#ifndef TH04_OP_CDG_SLOTS_HPP
#define TH04_OP_CDG_SLOTS_HPP

// Slot numbers used by the TH04 OP title and option menus.
enum {
    CDG_NUMERAL = 0,
    CDG_MAIN_GAME = 10,
    CDG_MAIN_EXTRA = 11,
    CDG_MAIN_REGIST_VIEW = 12,
    CDG_MAIN_MUSICROOM = 13,
    CDG_MAIN_OPTION = 14,
    CDG_QUIT = 15,
    CDG_OPTION_LABEL_RANK = 16,
    CDG_OPTION_LABEL_LIVES = 17,
    CDG_OPTION_LABEL_BOMBS = 18,
    CDG_OPTION_LABEL_BGM = 19,
    CDG_OPTION_LABEL_SE = 20,
    CDG_OPTION_VALUE_RANK = 21,
    CDG_OPTION_VALUE_BGM = 25,
    CDG_OPTION_VALUE_OFF = 28,
    CDG_OPTION_VALUE_SE_BEEP = 29,
    CDG_OPTION_VALUE_SE_FM = 30,
    CDG_OPTION_RESET = 31,
    CDG_OPTION_TURBO = 32,
    CDG_OPTION_SLOW = 33,
    CDG_CURSOR_LEFT = 35,
    CDG_CURSOR_RIGHT = 36,
    CDG_PIC = 40,
};

#endif
