#ifndef TH04_MAIN_SPRITES_MAIN_PAT_HPP
#define TH04_MAIN_SPRITES_MAIN_PAT_HPP

#if (GAME == 5)
// Constants used by retained TH05 compiler-calibration branches in shared
// TH04-maintained code.
static const int PAT_EXPLOSION_BIG = 3;
static const int PAT_ENEMY_KILL = 4;
static const int PAT_ENEMY_KILL_last = 11;
static const int PAT_BULLET16_D = 52;
static const int PAT_BULLET16_D_BLUE = PAT_BULLET16_D;
static const int PAT_BULLET16_D_BLUE_last = 67;
static const int PAT_BULLET16_D_GREEN = 68;
static const int PAT_BULLET16_D_GREEN_last = 83;
static const int PAT_BULLET16_V_RED = 84;
static const int PAT_BULLET16_V_RED_last = 115;
static const int PAT_BULLET16_V_BLUE = 116;
static const int PAT_BULLET_ZAP = 152;
static const int PAT_DECAY_PELLET = 156;
static const int PAT_DECAY_BULLET16 = 160;
static const int PAT_EXPLOSION_SMALL = 164;
#else
#include "src/main/sprites/cels.hpp"

typedef enum {
	M4C_STILL,
	M4C_CAST_1,
	M4C_CAST_2,
	M4C_CAST_3,
	M4C_CELS,
} midboss4_cel_t;

#define REIMU_ORB_CELS 4
#define YUUKA6_CHASECROSS_CELS 4

typedef enum {
	PAT_EXPLOSION_BIG = 3,
	PAT_ENEMY_KILL,
	PAT_ENEMY_KILL_last = (PAT_ENEMY_KILL + ENEMY_KILL_CELS - 1),
	PAT_CLOUD_BULLET16_BLUE = 20,
	PAT_CLOUD_BULLET16_BLUE_last = (
		PAT_CLOUD_BULLET16_BLUE + BULLET_CLOUD_CELS - 1
	),
	PAT_CLOUD_BULLET16_RED,
	PAT_OPTION_REIMU = 38,
	PAT_OPTION_MARISA,
	PAT_HITSHOT,
	PAT_HITSHOT_last = (PAT_HITSHOT + HITSHOT_CELS - 1),
	PAT_ITEM,

	PAT_BULLET16_N_OUTLINED_BALL_WHITE = 52,
	PAT_BULLET16_N_OUTLINED_BALL_RED,
	PAT_BULLET16_N_OUTLINED_BALL_GREEN,
	PAT_BULLET16_N_OUTLINED_BALL_BLUE,
	PAT_BULLET16_N_STAR,
	PAT_BULLET16_N_BALL_BLUE,
	PAT_BULLET16_N_SMALL_BALL_YELLOW,
	PAT_BULLET16_N_CROSS_YELLOW,
	PAT_BULLET16_N_SMALL_BALL_RED,
	PAT_BULLET16_N_BALL_RED,
	PAT_BULLET16_N_HEART_BALL_RED,

	PAT_EXPLOSION_SMALL = 68,
	PAT_SHOT_LASER_RING = 70,
	PAT_SHOT_LASER_RING_last = (PAT_SHOT_LASER_RING + SHOT_CELS - 1),
	PAT_BULLET_ZAP,
	PAT_BULLET_ZAP_last = (PAT_BULLET_ZAP + BULLET_ZAP_CELS - 1),
	PAT_BULLET16_D,
	PAT_BULLET16_D_BLUE = PAT_BULLET16_D,
	PAT_BULLET16_D_BLUE_last = (PAT_BULLET16_D_BLUE + BULLET_D_CELS - 1),
	PAT_BULLET16_D_YELLOW,
	PAT_BULLET16_D_YELLOW_last = (
		PAT_BULLET16_D_YELLOW + BULLET_D_CELS - 1
	),
	PAT_DECAY_PELLET,
	PAT_DECAY_PELLET_last = (PAT_DECAY_PELLET + BULLET_DECAY_CELS - 1),
	PAT_DECAY_BULLET16,
	PAT_DECAY_BULLET16_last = (
		PAT_DECAY_BULLET16 + BULLET_DECAY_CELS - 1
	),

	PAT_STAGE = 128,
	PAT_MIDBOSS4_STILL_LEFT = (PAT_STAGE + 28 + M4C_STILL),
	PAT_MIDBOSS4_STILL_LEFT_last = (
		PAT_MIDBOSS4_STILL_LEFT + M4C_CELS - 1
	),
	PAT_MIDBOSS4_STILL_RIGHT,
	PAT_MIDBOSS4_STILL_RIGHT_last = (
		PAT_MIDBOSS4_STILL_RIGHT + M4C_CELS - 1
	),
	PAT_REIMU_ORB_BLUE = (PAT_STAGE + 12),
	PAT_REIMU_ORB_BLUE_last = (PAT_REIMU_ORB_BLUE + REIMU_ORB_CELS - 1),
	PAT_REIMU_ORB_YELLOW,
	PAT_REIMU_ORB_YELLOW_last = (
		PAT_REIMU_ORB_YELLOW + REIMU_ORB_CELS - 1
	),
	PAT_MARISA_BIT = (PAT_STAGE + 8),

	PAT_YUUKA6_PARASOL_BACK_OPEN = 128,
	PAT_YUUKA6_PARASOL_BACK_HALFOPEN = 130,
	PAT_YUUKA6_PARASOL_BACK_HALFCLOSED = 132,
	PAT_YUUKA6_PARASOL_BACK_CLOSED = 134,
	PAT_YUUKA6_PARASOL_LEFT_PULL = 136,
	PAT_YUUKA6_PARASOL_FORWARD_CLOSED = 138,
	PAT_YUUKA6_PARASOL_FORWARD_OPEN = 140,
	PAT_YUUKA6_PARASOL_SHIELD_0 = 142,
	PAT_YUUKA6_PARASOL_SHIELD_1 = 144,
	PAT_YUUKA6_PARASOL_SHIELD_2 = 146,
	PAT_YUUKA6_PARASOL_SHIELD_3 = 148,
	PAT_YUUKA6_PARASOL_LEFT = 150,
	PAT_YUUKA6_PARASOL_LEFT_FORWARD_PULL = 152,
	PAT_YUUKA6_PARASOL_SPIN_BACK_0 = 154,
	PAT_YUUKA6_PARASOL_SPIN_BACK_1 = 156,
	PAT_YUUKA6_PARASOL_SPIN_BACK_2 = 158,
	PAT_YUUKA6_PARASOL_SPIN_BACK_3 = 160,
	PAT_YUUKA6_PARASOL_SPIN_BACK_4 = 162,
	PAT_YUUKA6_PARASOL_SPIN_BACK_5 = 164,
	PAT_YUUKA6_PARASOL_SPIN_BACK_6 = 166,
	PAT_YUUKA6_PARASOL_SPIN_BACK_7 = 168,
	PAT_YUUKA6_PARASOL_SPIN_BACK_8 = 170,
	PAT_YUUKA6_PARASOL_SPIN_BACK_9 = 172,
	PAT_YUUKA6_VANISH_0 = 174,
	PAT_YUUKA6_VANISH_1 = 176,
	PAT_YUUKA6_VANISH_2 = 178,
	PAT_YUUKA6_VANISH_3 = 180,
	PAT_YUUKA6_CHASECROSS = 186,
	PAT_YUUKA6_CHASECROSS_last = (
		PAT_YUUKA6_CHASECROSS + YUUKA6_CHASECROSS_CELS - 1
	),
	PAT_GENGETSU_TIPPING = PAT_STAGE,
	PAT_STAGE_last = 255,

	_main_patnum_t_FORCE_INT16 = 0x7FFF,
} main_patnum_t;

#endif

#endif
